<!DOCTYPE html>
<html>
<head>
	<title>timeline</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="/libs/bootstrap/css/bootstrap.css">
</head>

<body>
	<div>Test</div>
	<div id="content">
	
	</div>
	<!--<div id="test"><input type="text" id="test-input" placeholder="my test input" value="hello world" /></div>-->
  	<script src="./libs/jquery/jquery-2.0.3.min.js"></script>
  	<script src="./libs/swig.min.js"></script>
  	<script src="./libs/jstorage.min.js"></script>
  	<script data-main="/app" src="./libs/require.js"></script>
</body>
</html>
